### ISSUE TITLE
Setup labels.yaml in .github

### ISSUE THREAD

**Issue by nueeg** [nueegcompany/.github#2]
Please add a labels.yaml to the .github --> for reference check this file. 

https://github.com/dslp/dslp-repo-template/blob/main/.github/labels.yaml

**Comment by nueeg** [comment]
@bhydemi I have adjusted the Github Project boards. Response from you and Nitin on Issue labels to be incorporated here.

**Comment by bhydemi** [comment]
PR created here based on the repo, however we can enhance later on @nueeg

**Comment by nueeg** [comment]
Approved
